experiment_name: auto
secrets_file: /scratch/catdx/.secrets

model_config:
  attention_probs_dropout_prob: 0.0
  freeze: []
  hidden_act: gelu_fast
  hidden_dropout_prob: 0.0
  image_size: ${trainer_config.resize_to}
  num_labels: 1
  num_attention_heads: 12
  num_channels: 1
  num_frames: 32
  num_hidden_layers: 12
  problem_type: regression
  tubelet_size: [2, 16, 16]
  video_size:
    - ${model_config.num_frames}
    - ${model_config.image_size}
    - ${model_config.image_size}
  model_name_or_path: "/scratch/catdx/outputs/2025-05-10/19-39-08/cone2eunsup_sz224_lr1e-05_cs0.15_wd0.001_2/checkpoint-14000"

trainer_config:
  auto_find_batch_size: false
  gather_loss: true
  contrastive_sigma: 0.15
  contrastive_method: expw
  do_eval: true
  do_predict: true
  is_unsupervised: true
  dataset_folder: RVENetCropRszMp4
  training_mode: end_to_end_contrastive
  eval_strategy: epoch
  fp16: true
  kernel_type: gaussian
  learning_rate: 1e-5
  logging_strategy: epoch
  lr_scheduler_type: step
  lr_scheduler_kwargs:
    step_size_epochs: 0.2
    gamma: 0.5
  metric_for_best_model: loss
  num_train_epochs: 0
  per_device_eval_batch_size: 16
  per_device_train_batch_size: 16
  remove_unused_columns: false
  report_to: wandb
  resize_to: 224
  resume_from_checkpoint: false
  output_dir: ${experiment_name}
  save_strategy: steps
  save_steps: 500
  warmup_steps: 0
  weight_decay: 1e-3
